meyveler = ["Elma", "Çilek", "Armut"]
print(meyveler)
print(meyveler[0])
print(meyveler[1])
print(meyveler[2])
print(meyveler[-1])
print(type(meyveler))
meyveler.append("Muz")
print(meyveler)
meyveler.insert(1, "Karpuz")
print(meyveler)
meyveler.remove("Armut")
meyveler.pop(0)
print(meyveler)
meyveler.sort()
print(meyveler)
print(len(meyveler))